import { useState, useEffect } from 'react'
import { AlignLeft, Copy, Trash2, Plus, Printer } from 'lucide-react'
import SEOHead from '../../components/SEOHead.jsx'
import CopyButton from '../../components/CopyButton.jsx'
import * as storage from '../../utils/storage.js'

const PROPOSAL_KEY = 'proposal:autosave'
const DEFAULT_TERMS = 'Payment due upon completion. All work is non-refundable unless agreed otherwise.'

function esc(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export default function ProposalBuilder() {
  const [sections, setSections] = useState([
    { id: 1, title: 'Executive Summary', content: '', order: 1, hint: 'Provide a brief overview of who you are and what you\'re proposing.' },
    { id: 2, title: 'Problem Statement', content: '', order: 2, hint: 'Describe the client\'s challenges or pain points.' },
    { id: 3, title: 'Proposed Solution', content: '', order: 3, hint: 'Explain your approach and solution to address their problem.' },
    { id: 4, title: 'Scope of Work', content: '', order: 4, hint: 'List all deliverables and activities included.' },
    { id: 5, title: 'Timeline', content: '', order: 5, hint: 'Outline the project timeline and key milestones.' },
    { id: 6, title: 'Investment / Pricing', content: '', order: 6, hint: 'Detail the pricing structure and payment terms.' },
    { id: 7, title: 'About You / Your Team', content: '', order: 7, hint: 'Share your qualifications, experience, and team.' },
    { id: 8, title: 'Terms & Conditions', content: DEFAULT_TERMS, order: 8, hint: 'Include your standard terms.' },
    { id: 9, title: 'Call to Action / Next Steps', content: '', order: 9, hint: 'Tell them how to proceed and accept your proposal.' },
  ])

  const [expanded, setExpanded] = useState(new Set(['1']))
  const [showWordTargets, setShowWordTargets] = useState(false)

  // Auto-save every 3 seconds
  useEffect(() => {
    const timer = setInterval(() => {
      storage.setItem(PROPOSAL_KEY, sections)
    }, 3000)
    return () => clearInterval(timer)
  }, [sections])

  // Load on mount
  useEffect(() => {
    const saved = storage.getItem(PROPOSAL_KEY)
    if (saved && Array.isArray(saved)) {
      setSections(saved)
    }
  }, [])

  const updateSection = (id, field, value) => {
    setSections(sections.map(s => s.id === id ? { ...s, [field]: value } : s))
  }

  const toggleExpanded = (id) => {
    const newExpanded = new Set(expanded)
    if (newExpanded.has(String(id))) {
      newExpanded.delete(String(id))
    } else {
      newExpanded.add(String(id))
    }
    setExpanded(newExpanded)
  }

  const totalWords = sections.reduce((sum, s) => sum + (s.content.trim().split(/\s+/).length || 0), 0)

  const wordCount = (text) => text.trim() ? text.trim().split(/\s+/).length : 0

  const clear = () => {
    if (confirm('Clear all proposal content?')) {
      setSections(sections.map(s => ({ ...s, content: s.id === 8 ? DEFAULT_TERMS : '' })))
      storage.removeItem(PROPOSAL_KEY)
    }
  }

  const handlePrint = () => {
    const filledSections = sections.filter(s => s.content.trim())
    if (filledSections.length === 0) return

    const sectionHtml = filledSections.map(s =>
      `<div style="page-break-inside:avoid;break-inside:avoid;margin-bottom:20px">
        <h2 style="font-size:16px;font-weight:600;color:#111827;margin:0 0 8px;padding-bottom:6px;border-bottom:1px solid #e5e7eb">${esc(s.title)}</h2>
        <div style="font-size:13px;color:#374151;white-space:pre-wrap;line-height:1.7">${esc(s.content)}</div>
      </div>`
    ).join('')

    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Proposal</title>
      <style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;max-width:800px;margin:0 auto;padding:32px;color:#374151}
      @media print{body{padding:0}}</style></head><body>
      <h1 style="font-size:22px;margin-bottom:4px;color:#111827">Proposal</h1>
      <p style="color:#6b7280;font-size:13px;margin-top:0">${totalWords} words &middot; ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>
      <hr style="border:none;border-top:1px solid #e5e7eb;margin:16px 0">
      ${sectionHtml}
      <p style="margin-top:32px;font-size:11px;color:#9ca3af;text-align:center">Generated by UnTrackt Proposal Builder</p>
      </body></html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)

    let iframe = document.getElementById('proposal-print-frame')
    if (iframe) iframe.remove()
    iframe = document.createElement('iframe')
    iframe.id = 'proposal-print-frame'
    iframe.style.cssText = 'position:fixed;top:-10000px;left:-10000px;width:800px;height:600px'
    document.body.appendChild(iframe)
    iframe.src = url

    iframe.onload = () => {
      try {
        iframe.contentWindow.print()
      } catch {
        window.open(url, '_blank')
      }
      setTimeout(() => { iframe.remove(); URL.revokeObjectURL(url) }, 5000)
    }
  }

  return (
    <>
      <SEOHead
        title="Proposal Builder | UnTrackt"
        description="Build professional proposals with auto-save. Structured sections with writing tips, live word count, and print to PDF."
        path="/tools/proposal-builder"
        toolName="Proposal Builder"
      />


      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Sidebar */}
        <div className="lg:col-span-1 space-y-4">
          <div className="bg-white p-6 rounded-xl border border-gray-200 sticky top-6 space-y-4">
            <div>
              <p className="text-sm text-gray-600 mb-1">Total Words</p>
              <p className="text-3xl font-bold text-gray-900">{totalWords}</p>
            </div>

            <div className="pt-4 border-t border-gray-200 space-y-2">
              <button
                onClick={handlePrint}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 text-white font-medium text-sm hover:bg-blue-700 transition-colors w-full justify-center"
              >
                <Printer className="w-4 h-4" />
                Print / Save as PDF
              </button>
              <button onClick={() => setShowWordTargets(!showWordTargets)} className="btn-secondary w-full text-sm">
                {showWordTargets ? 'Hide' : 'Show'} Targets
              </button>
              <button onClick={clear} className="btn-secondary w-full text-sm bg-red-50 text-red-600 hover:bg-red-100">
                Clear All
              </button>
            </div>

            {showWordTargets && (
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 text-xs text-blue-900 space-y-1">
                <p className="font-semibold mb-2">Suggested Word Counts:</p>
                {[
                  ['Executive Summary', 75],
                  ['Problem Statement', 150],
                  ['Solution', 200],
                  ['Investment', 100],
                  ['About Us', 150],
                ].map(([name, target]) => (
                  <p key={name}><span className="font-medium">{name}:</span> ~{target} words</p>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Main Content */}
        <div id="proposal-preview" className="lg:col-span-2 space-y-4">
          {sections.map((section) => (
            <div key={section.id} className="bg-white rounded-xl border border-gray-200 overflow-hidden">
              <button
                onClick={() => toggleExpanded(section.id)}
                className="w-full px-6 py-4 flex items-center justify-between hover:bg-gray-50 transition-colors"
              >
                <h3 className="font-semibold text-lg text-gray-900 text-left">{section.title}</h3>
                <div className="flex items-center gap-2 text-xs text-gray-500">
                  <span className="px-2 py-1 bg-gray-100 rounded">{wordCount(section.content)} words</span>
                  <span className={`transition-transform ${expanded.has(String(section.id)) ? 'rotate-180' : ''}`}>
                    ▼
                  </span>
                </div>
              </button>

              {expanded.has(String(section.id)) && (
                <div className="px-6 py-4 border-t border-gray-200 space-y-3">
                  {section.hint && (
                    <div className="text-xs text-blue-600 bg-blue-50 p-2 rounded italic">
                      💡 {section.hint}
                    </div>
                  )}
                  <textarea
                    value={section.content}
                    onChange={e => updateSection(section.id, 'content', e.target.value)}
                    className="input-field w-full textarea resize-none"
                    rows="8"
                    placeholder={`Write your ${section.title.toLowerCase()}...`}
                  />
                  <div className="flex items-center justify-between text-xs text-gray-500">
                    <span>{wordCount(section.content)} words</span>
                    <CopyButton text={section.content} label="Copy section" />
                  </div>
                </div>
              )}
            </div>
          ))}

          {/* Auto-save indicator */}
          <div className="text-xs text-gray-500 text-center py-4">
            ✓ Auto-saving to browser storage
          </div>
        </div>
      </div>
    </>
  )
}
